name: mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    emoji_picker_flutter: ^1.0.0
    http: ^1.1.0
    socket_io_client: ^2.0.3+1
    provider: ^6.1.1
    shared_preferences: ^2.2.2
    flutter_secure_storage: ^9.0.0
    intl: ^0.19.0
    image_picker: ^1.0.7
    cached_network_image: ^3.3.1
    flutter_screenutil: ^5.9.0
    cupertino_icons: ^1.0.2
    csv: ^5.1.1
    path_provider: ^2.1.2
    share_plus: ^7.2.1
    fl_chart: ^0.66.0
    photo_view: ^0.14.0
    flutter_markdown: ^0.6.20
    permission_handler: ^11.3.0
    url_launcher: ^6.1.12
    flutter_pdfview: ^1.3.2
    dio: ^5.4.1
    video_player: ^2.8.2
    chewie: ^1.7.5
    path: ^1.8.3
    open_file: ^3.3.2
    video_compress: ^3.1.2
    file_picker: ^10.0.0
    qr_flutter: ^4.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
